# Generated by Django 5.1 on 2024-10-09 17:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('telephone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма перевода')),
                ('type_transfer', models.CharField(choices=[('using your phone', 'С помощью телефона'), ('by map', 'По карте'), ('using QR code', 'Через QR код')], default='using your phone', max_length=20, verbose_name='Тип перевода')),
                ('comment', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(255, 'Комментарий не может быть длиннее 255 символов.')], verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('payment_id', models.CharField(max_length=255, unique=True, verbose_name='ID платежа')),
                ('is_accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Разовый перевод',
                'verbose_name_plural': 'Разовые переводы',
            },
        ),
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0, message='Should be positive value')], verbose_name='Сумма')),
                ('frequency', models.CharField(choices=[('monthly', 'Ежемесячно'), ('quarterly', 'Ежеквартально'), ('yearly', 'Ежегодно')], default='monthly', max_length=20, verbose_name='Периодичность')),
                ('next_payment_date', models.DateTimeField(verbose_name='Дата следующего платежа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_payments', to='transfer_app.paymentmodel', verbose_name='Платеж')),
            ],
            options={
                'verbose_name': 'Авто перевод',
                'verbose_name_plural': 'Авто переводы',
            },
        ),
    ]
