# Generated by Django 5.1 on 2024-10-14 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('telephone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма перевода')),
                ('payment_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True, verbose_name='ID платежа')),
                ('payment_frequency', models.CharField(choices=[('one-time', 'Разово'), ('monthly', 'Ежемесячно')], max_length=15)),
                ('type_transfer', models.CharField(choices=[('using your phone', 'С помощью телефона'), ('by map', 'По карте'), ('using QR code', 'Через QR код')], default='using your phone', max_length=50, verbose_name='Тип перевода')),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
