# Generated by Django 5.1 on 2024-10-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_id',
            field=models.CharField(help_text='ID платежа, пример: 6dec59c0-c176-4132-85b1-a161e5c4bd7f', max_length=100, unique=True, verbose_name='ID платежа'),
        ),
    ]
