# Generated by Django 5.1 on 2024-09-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentModel',
        ),
    ]
