# Generated by Django 5.1 on 2024-10-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_app', '0002_alter_paymentmodel_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='status',
            field=models.CharField(default='pending', help_text='Текст не более 20 символов', max_length=20, verbose_name='Статус платежа'),
        ),
    ]
