# Generated by Django 5.1 on 2024-10-16 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_app', '0003_alter_paymentmodel_comment_alter_paymentmodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='ID платежа'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='type_transfer',
            field=models.CharField(choices=[('phone_number', 'С помощью телефона'), ('bank_card', 'По карте'), ('qr_code', 'Через QR код')], default='phone_number', max_length=50, verbose_name='Тип перевода'),
        ),
    ]
