# Generated by Django 5.1 on 2024-10-03 18:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_app', '0003_recurringpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmodel',
            options={'verbose_name': 'Разовый перевод', 'verbose_name_plural': 'Разовые переводы'},
        ),
        migrations.AlterModelOptions(
            name='recurringpayment',
            options={'verbose_name': 'Авто перевод', 'verbose_name_plural': 'Авто переводы'},
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0, message='Should be positive value')], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Ежемесячно'), ('quarterly', 'Ежеквартально'), ('yearly', 'Ежегодно')], default='monthly', max_length=20, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='next_payment_date',
            field=models.DateTimeField(verbose_name='Дата следующего платежа'),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_payments', to='transfer_app.paymentmodel', verbose_name='Платеж'),
        ),
    ]
