# Generated by Django 5.1 on 2024-10-17 19:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_app', '0003_alter_paymentmodel_comment_alter_paymentmodel_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_id',
            field=models.CharField(default=uuid.uuid4, max_length=45, unique=True, verbose_name='ID платежа'),
        ),
    ]
