# Generated by Django 5.1 on 2024-10-16 18:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_app', '0005_alter_paymentmodel_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='ID платежа'),
        ),
    ]
