# Generated by Django 5.1 on 2024-10-18 23:40

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Текст не более 255 символов', max_length=255, verbose_name='Адрес')),
                ('phone_1', phonenumber_field.modelfields.PhoneNumberField(help_text='Введите Первый номер телефона ', max_length=128, region='RU', verbose_name='Первый номер телефона')),
                ('phone_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Введите Второй номер телефона (необязательно)', max_length=128, null=True, region='RU', verbose_name='Второй номер телефона')),
                ('email', models.EmailField(help_text='Введите email: example@mail.com', max_length=254, verbose_name='email ')),
                ('phone_for_media', phonenumber_field.modelfields.PhoneNumberField(help_text='Введите Телефон для СМИ ', max_length=128, region='RU', verbose_name='Телефон для СМИ')),
                ('email_for_media', models.EmailField(help_text='Введите email: example@mail.com', max_length=254, verbose_name='email  для СМИ')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
