# Generated by Django 5.1 on 2024-10-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contactpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='address',
            field=models.CharField(help_text='Текст, не более 255 символов', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='email',
            field=models.EmailField(help_text='Укажите электронную почту', max_length=200, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='for_media',
            field=models.CharField(help_text='Текст, не более 255 символов', max_length=255, verbose_name='Для СМИ'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='header',
            field=models.CharField(help_text='Текст, не более 200 символов', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='phones',
            field=models.CharField(help_text='Текст, не более 255 символов', max_length=255, verbose_name='Телефоны'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='short_description',
            field=models.TextField(help_text='Текст, не более 1000 символов', max_length=1000, verbose_name='Краткое описание'),
        ),
    ]
