# Generated by Django 5.1 on 2024-10-04 20:59

import contacts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_contactpage_for_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='phones',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_1',
            field=models.CharField(default='+79628368648', help_text='Первый номер телефона', max_length=20, validators=[contacts.validators.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_2',
            field=models.CharField(default='+79628368648', help_text='Второй номер телефона', max_length=20, validators=[contacts.validators.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='phone_for_media',
            field=models.CharField(default='+79628368648', help_text='Телефоны для СМИ', max_length=20, validators=[contacts.validators.validate_phone], verbose_name='Телефон для СМИ'),
        ),
    ]
