# Generated by Django 5.1 on 2024-10-11 18:08

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_contactpage_phones_contactpage_phone_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='phone_1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Первый номер телефона', max_length=128, region='RU', verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='phone_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Второй номер телефона', max_length=128, null=True, region='RU', verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='phone_for_media',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Телефон для СМИ', max_length=128, region='RU', verbose_name='Телефон для СМИ'),
        ),
    ]
