# Generated by Django 5.1 on 2024-08-27 13:53

import django.core.validators
import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Текст без ограничений', verbose_name='Описание, чем был полезен Организации')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_published', models.BooleanField(default=True, help_text='Если уже неактуально, но может понадобиться, снимите флажок', verbose_name='Актуально на сайте')),
                ('name', models.CharField(help_text='Текст не более 100 символов', max_length=100, verbose_name='Название')),
                ('link', models.ImageField(blank=True, help_text='Добавьте логотип (необязательно)', null=True, upload_to=config.utils.docs_path, verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Текст без ограничений', verbose_name='Описание, чем был полезен Организации')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_published', models.BooleanField(default=True, help_text='Если уже неактуально, но может понадобиться, снимите флажок', verbose_name='Актуально на сайте')),
                ('name', models.CharField(help_text="Только буквы и '-' не более 50 символов", max_length=50, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Имя')),
                ('last_name', models.CharField(help_text="Только буквы и '-' не более 50 символов", max_length=50, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Фамилия')),
                ('link', models.ImageField(blank=True, help_text='Добавьте фото (необязательно)', null=True, upload_to=config.utils.docs_path, verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Человека',
                'verbose_name_plural': 'Люди',
            },
        ),
    ]
