# Generated by Django 5.1 on 2024-08-28 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Только буквы и '-' не более 50 символов", max_length=50, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Имя')),
                ('last_name', models.CharField(help_text="Только буквы и '-' не более 50 символов", max_length=50, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Фамилия')),
                ('email', models.EmailField(help_text='Введите email:', max_length=254, verbose_name='email')),
                ('is_accept', models.BooleanField(default=True, help_text='Принять пользовательское соглашение', verbose_name='Принято пользовательское соглашение')),
            ],
            options={
                'verbose_name': 'Волонтер',
                'verbose_name_plural': 'Волонтеры',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(help_text='Текст без ограничений', verbose_name='Чем была полезна:'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='description',
            field=models.TextField(help_text='Текст без ограничений', verbose_name='Роль в проекте'),
        ),
    ]
