# Generated by Django 5.1 on 2024-08-28 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0002_becomevolunteer_alter_company_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Только буквы и '-' не более 50 символов", max_length=50, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Имя')),
                ('last_name', models.CharField(help_text="Только буквы и '-' не более 50 символов", max_length=50, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Фамилия')),
                ('email', models.EmailField(help_text='Введите email: example@mail.com', max_length=254, verbose_name='email')),
                ('is_accept', models.BooleanField(default=True, verbose_name='Принято пользовательское соглашение')),
            ],
            options={
                'verbose_name': 'Волонтер',
                'verbose_name_plural': 'Волонтеры',
            },
        ),
        migrations.DeleteModel(
            name='BecomeVolunteer',
        ),
    ]
