# Generated by Django 5.1 on 2024-10-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0002_alter_company_link_alter_friend_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Если уже неактуально, но может понадобиться, снимите флажок', verbose_name='Актуально на сайте'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Если уже неактуально, но может понадобиться, снимите флажок', verbose_name='Актуально на сайте'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='is_accept',
            field=models.BooleanField(default=True, help_text=None, verbose_name='Принято пользовательское соглашение'),
        ),
    ]
