# Generated by Django 5.1 on 2024-09-06 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0003_volunteer_delete_becomevolunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Текст не более 100 символов', max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='last_name',
            field=models.CharField(help_text="Только буквы и '-' не более 50 символов", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(help_text="Только буквы и '-' не более 50 символов", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(help_text="Только буквы и '-' не более 50 символов", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(help_text="Только буквы и '-' не более 50 символов", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Имя'),
        ),
    ]
