# Generated by Django 5.1 on 2024-10-02 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0004_alter_company_name_alter_friend_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', help_text='Выберите пол', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(help_text='Текст, не более 300 символов', max_length=300, verbose_name='Чем была полезна:'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Текст не более 300 символов', max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='description',
            field=models.TextField(help_text='Текст, не более 300 символов', max_length=300, verbose_name='Роль в проекте'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='last_name',
            field=models.CharField(help_text="Только буквы и '-' не более 100 символов", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(help_text="Только буквы и '-' не более 100 символов", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(help_text="Только буквы и '-' не более 100 символов", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(help_text="Только буквы и '-' не более 100 символов", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Имя'),
        ),
    ]
