# Generated by Django 5.1 on 2024-10-04 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0005_friend_gender_alter_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='sur_name',
            field=models.CharField(help_text="Только буквы и '-' не более 100 символов", max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Отчество'),
        ),
    ]
