# Generated by Django 5.1 on 2024-10-03 17:33

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0005_friend_gender_alter_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='link',
            field=models.ImageField(blank=True, help_text='Добавьте фото (необязательно)', null=True, upload_to=config.utils.docs_path, verbose_name='Фото'),
        ),
    ]
