# Generated by Django 5.1 on 2024-10-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0006_friend_sur_name'),
        ('friends_app', '0006_volunteer_link'),
    ]

    operations = [
    ]
