<<<<<<< HEAD
# Generated by Django 5.1 on 2024-10-15 14:32
=======
# Generated by Django 5.1 on 2024-10-15 07:25
>>>>>>> origin/андрей

import config.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0008_alter_company_description_alter_friend_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(help_text='Не более 85 символов', max_length=85, verbose_name='Чем была полезна:'),
        ),
        migrations.AlterField(
            model_name='company',
            name='link',
            field=models.ImageField(blank=True, help_text='Добавьте Логотип (необязательно)', null=True, upload_to=config.utils.docs_path, verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Текст не более 255 символов', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='description',
            field=models.TextField(help_text='Не более 70 символов', max_length=70, verbose_name='Роль в проекте'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='last_name',
            field=models.CharField(help_text="Только буквы и ('-',) не более 100 символов ", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='link',
            field=models.ImageField(blank=True, help_text='Добавьте Фото (необязательно)', null=True, upload_to=config.utils.docs_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(help_text="Только буквы и ('-',) не более 100 символов ", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='sur_name',
            field=models.CharField(blank=True, help_text="Только буквы и (' ',) не более 100 символов (необязательно)", max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я ]+$')], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(help_text='Введите email: example@mail.com', max_length=254, verbose_name='email '),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(help_text="Только буквы и ('-',) не более 100 символов ", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='link',
            field=models.ImageField(blank=True, help_text='Добавьте Фото (необязательно)', null=True, upload_to=config.utils.docs_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(help_text="Только буквы и ('-',) не более 100 символов ", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Имя'),
        ),
    ]
