# Generated by Django 5.1 on 2024-10-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0009_alter_company_description_alter_company_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(help_text='Не более 70 символов', max_length=70, verbose_name='Чем была полезна:'),
        ),
    ]
