services:
  29_gifted_db:
    image: postgres:latest
    container_name: 29_gifted_db
    ports:
      - "${29_GIFTED_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${29_GIFTED_DB_USER}
      POSTGRES_PASSWORD: ${29_GIFTED_DB_PASS}
      POSTGRES_DB: ${29_GIFTED_DB_NAME}
    volumes:
      - ${29_GIFTED_DB_VOLUME}:/var/lib/postgresql/data

  29_gifted_web:
    build:
      context: .
    container_name: 29_gifted_django_app
    volumes:
      - ${29_GIFTED_APP_VOLUME}:/app
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DATABASE_URL=postgres://${29_GIFTED_DB_USER}:${29_GIFTED_DB_PASS}@${29_GIFTED_DB_HOST}:${29_GIFTED_DB_PORT}/${29_GIFTED_DB_NAME}
    depends_on:
      - 29_gifted_db