services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build:
      context: .
    container_name: django_app
    volumes:
      - ${APP_VOLUME}:/app
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - db
    env_file:
      - .env