services:
  gifted_29_redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - gifted_29_local_network

  gifted_29_celery_worker:
    build:
      context: .
    command: celery -A config worker -l info
    depends_on:
      - gifted_29_redis
      - gifted_29_db
    networks:
      - gifted_29_local_network
      
  gifted_29_db:
    image: postgres:latest
    container_name: gifted_29_db
    ports:
      - "${GIFTED_29_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${GIFTED_29_DB_USER}
      POSTGRES_PASSWORD: ${GIFTED_29_DB_PASS}
      POSTGRES_DB: ${GIFTED_29_DB_NAME}
    volumes:
      - ${GIFTED_29_DB_VOLUME}:/var/lib/postgresql/data/pgdata
    networks:
      - gifted_29_local_network

  gifted_29_django_app:
    build:
      context: .
    container_name: gifted_29_django_app
    volumes:
      - ${GIFTED_29_APP_VOLUME}:/app
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DATABASE_URL=postgres://${GIFTED_29_DB_USER}:${GIFTED_29_DB_PASS}@${GIFTED_29_DB_HOST}:${GIFTED_29_DB_PORT}/${GIFTED_29_DB_NAME}
    depends_on:
      - gifted_29_db
      - gifted_29_redis
      - gifted_29_celery_worker
    logging:
      driver: loki
      options:
        loki-url: http://host.docker.internal:3100/loki/api/v1/push
    networks:
      - gifted_29_local_network
      - default


  grafana:
    image: grafana/grafana:9.2.15
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
    - "3001:3000"
  loki:
    image: grafana/loki:2.8.0
    ports:
    - "3100:3100"
    networks:
      - gifted_29_local_network
  
networks:
  default:
    name: nginx_network
    external: true
  gifted_29_local_network:
    name: gifted_29_network
