# Generated by Django 5.1 on 2024-10-17 21:00

import config.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_developer_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='photo',
        ),
        migrations.AlterField(
            model_name='developer',
            name='first_name',
            field=models.CharField(help_text="Только буквы и ('-',) не более 50 символов ", max_length=50, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='last_name',
            field=models.CharField(help_text="Только буквы и ('-',) не более 50 символов ", max_length=50, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='role',
            field=models.CharField(help_text='Текст не более 100 символов', max_length=100, verbose_name='Роль в проекте'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='surname',
            field=models.CharField(blank=True, help_text="Только буквы и (' ',) не более 50 символов (необязательно)", max_length=50, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я ]+$')], verbose_name='Отчество'),
        ),
        migrations.CreateModel(
            name='DeveloperImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ImageField(help_text='Добавьте Изображение ', upload_to=config.utils.docs_path, verbose_name='Изображение')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='team.developer', verbose_name='Разработчик')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
