# Generated by Django 5.1 on 2024-08-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_event', models.CharField(max_length=500, verbose_name='название мероприятия')),
                ('description_of_event', models.TextField(verbose_name='описание мероприятия')),
                ('address_of_event', models.CharField(blank=True, max_length=500, null=True, verbose_name='адрес проведения мероприятия')),
                ('time_of_event', models.DateTimeField(auto_now=True, null=True, verbose_name='время проведения мероприятия')),
                ('photos_from_event', models.ImageField(blank=True, null=True, upload_to='event/photo/%Y/%m/%d', verbose_name='фото с мероприятия')),
                ('video_from_event', models.FileField(blank=True, null=True, upload_to='event/video/%Y/%m/%d', verbose_name='видео с мероприятия')),
            ],
            options={
                'verbose_name': 'мероприятие',
                'verbose_name_plural': 'мероприятия',
            },
        ),
    ]
