# Generated by Django 5.1 on 2024-08-19 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='photos_from_event',
        ),
        migrations.AlterField(
            model_name='events',
            name='time_of_event',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время проведения мероприятия'),
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='event/photo/%Y/%m/%d')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events_app.events')),
            ],
            options={
                'verbose_name': 'фотография мероприятия',
                'verbose_name_plural': 'фотографии мероприятия',
            },
        ),
    ]
