# Generated by Django 5.1 on 2024-08-20 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_remove_events_photos_from_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='video_from_event',
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='events_app.events'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='events/photo/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='EventVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='events/video/%Y/%m/%d')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='events_app.events')),
            ],
            options={
                'verbose_name': 'видео мероприятия',
                'verbose_name_plural': 'видео мероприятия',
            },
        ),
    ]
