# Generated by Django 5.1 on 2024-08-20 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_remove_events_video_from_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLinkVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_video', models.TextField(verbose_name='ссылка на видео')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_video', to='events_app.events')),
            ],
            options={
                'verbose_name': 'ссылка на видео мероприятия',
                'verbose_name_plural': 'ссылки на видео мероприятия',
            },
        ),
    ]
