# Generated by Django 5.1 on 2024-10-20 10:24

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0004_alter_eventphoto_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvideo',
            name='link',
            field=models.FileField(blank=True, help_text='Добавьте Видео мероприятия (необязательно)', null=True, upload_to=config.utils.docs_path, validators=[config.utils.validate_video_size], verbose_name='Видео мероприятия'),
        ),
    ]
