# Generated by Django 5.1 on 2024-08-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0004_eventlinkvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlinkvideo',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата добавления'),
        ),
    ]
