# Generated by Django 5.1 on 2024-08-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0005_eventlinkvideo_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='time_of_event',
            new_name='date_time_of_event',
        ),
    ]
