# Generated by Django 5.1 on 2024-08-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0006_rename_time_of_event_events_date_time_of_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
