# Generated by Django 5.1 on 2024-10-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0006_alter_eventlinkvideo_link_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='terms_agreed',
            field=models.BooleanField(default=True, help_text=None, verbose_name='Согласие с условиями'),
        ),
    ]
