# Generated by Django 5.1 on 2024-08-25 16:39

import events_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0007_rename_events_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventphoto',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='eventvideo',
            name='video',
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='link',
            field=models.ImageField(blank=True, null=True, upload_to=events_app.models.docs_path),
        ),
        migrations.AddField(
            model_name='eventvideo',
            name='link',
            field=models.FileField(blank=True, null=True, upload_to=events_app.models.docs_path),
        ),
    ]
