# Generated by Django 5.1 on 2024-08-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0008_remove_eventphoto_photo_remove_eventvideo_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address_of_event',
            field=models.CharField(blank=True, help_text='Текст не более 500 символов', max_length=500, null=True, verbose_name='Адрес проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time_of_event',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_of_event',
            field=models.TextField(help_text='Текст без ограничений', verbose_name='Описание мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_of_event',
            field=models.CharField(help_text='Текст не более 200 символов', max_length=200, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventlinkvideo',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='eventlinkvideo',
            name='link_video',
            field=models.TextField(verbose_name='Ссылка на видео'),
        ),
    ]
