# Generated by Django 5.1 on 2024-09-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0009_alter_event_address_of_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_of_event',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time_of_event',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_of_event',
            field=models.CharField(help_text='Текст не более 300 символов', max_length=300, verbose_name='Название мероприятия'),
        ),
    ]
