# Generated by Django 5.1 on 2024-09-10 15:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0009_alter_event_address_of_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_of_event',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time_of_event',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_of_event',
            field=models.CharField(help_text='Текст не более 300 символов', max_length=300, verbose_name='Название мероприятия'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(1, 'Имя должно быть не менее 1 символа'), django.core.validators.MaxLengthValidator(64, 'Имя должно быть не более 64 символов'), django.core.validators.RegexValidator(message='Имя может содержать только кириллицу, латиницу, пробел и тире', regex='^[A-Za-zА-Яа-я\\- ]+$'), django.core.validators.RegexValidator(message='Нельзя использовать кириллицу и латиницу одновременно', regex='^(?!.[A-Za-z].[А-Яа-я]|[А-Яа-я].[A-Za-z]).$'), django.core.validators.RegexValidator(message='Нельзя использовать больше 2х спец символов подряд', regex='^(?!.[\\d\\W]{3}).$')], verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(1, 'Фамилия должна быть не менее 1 символа'), django.core.validators.MaxLengthValidator(64, 'Фамилия должна быть не более 64 символов'), django.core.validators.RegexValidator(message='Фамилия может содержать только кириллицу, латиницу, пробел и тире', regex='^[A-Za-zА-Яа-я\\- ]+$'), django.core.validators.RegexValidator(message='Нельзя использовать кириллицу и латиницу одновременно', regex='^(?!.[A-Za-z].[А-Яа-я]|[А-Яа-я].[A-Za-z]).$'), django.core.validators.RegexValidator(message='Нельзя использовать больше 2х спец символов подряд', regex='^(?!.[\\d\\W]{3}).$')], verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.MaxLengthValidator(254, 'Email не может быть длиннее 254 символов'), django.core.validators.RegexValidator(message='Некорректный email адрес', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')], verbose_name='Электронная почта')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время регистрации')),
                ('terms_agreed', models.BooleanField(default=False, verbose_name='Согласие с условиями')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events_app.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
            },
        ),
    ]
