# Generated by Django 5.1 on 2024-09-18 18:10

import django.core.validators
import events_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0011_alter_registration_options_alter_registration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='comment',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(200, 'Комментарий не может быть длиннее 200 символов.'), events_app.validators.validate_comment], verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.MaxLengthValidator(254, 'Email не может быть длиннее 254 символов'), events_app.validators.validate_email], verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(1, 'Имя должно быть не менее 1 символа'), django.core.validators.MaxLengthValidator(64, 'Имя должно быть не более 64 символов'), events_app.validators.validate_name_or_surname, events_app.validators.validate_no_mixed_scripts, events_app.validators.validate_number_of_spaces_or_dashes], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(1, 'Фамилия должна быть не менее 1 символа'), django.core.validators.MaxLengthValidator(64, 'Фамилия должна быть не более 64 символов'), events_app.validators.validate_name_or_surname, events_app.validators.validate_no_mixed_scripts, events_app.validators.validate_number_of_spaces_or_dashes], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=20, validators=[events_app.validators.validate_phone], verbose_name='Телефон'),
        ),
    ]
