# Generated by Django 5.1 on 2024-09-28 16:09

import django.core.validators
import events_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0012_alter_registration_comment_alter_registration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='comment',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(200, 'Комментарий не может быть длиннее 200 символов.'), events_app.validators.validate_no_mixed_scripts, events_app.validators.validate_number_of_spaces_or_dashes, events_app.validators.validate_comment], verbose_name='Комментарий'),
        ),
    ]
