# Generated by Django 5.1 on 2024-10-17 19:41

import django.core.validators
import events_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0014_alter_registration_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description_of_event',
            field=models.TextField(help_text='Не более 2000 символов', max_length=2000, verbose_name='Описание мероприятия'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='comment',
            field=models.TextField(blank='True', validators=[django.core.validators.MaxLengthValidator(200, 'Комментарий не может быть длиннее 200 символов.'), events_app.validators.validate_no_mixed_scripts, events_app.validators.validate_number_of_spaces_or_dashes, events_app.validators.validate_comment], verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(1, 'Имя должно быть не менее 1 символа'), django.core.validators.MaxLengthValidator(64, 'Имя должно быть не более 64 символов'), events_app.validators.validate_name_or_surname, events_app.validators.validate_no_mixed_scripts, events_app.validators.validate_number_of_spaces_or_dashes], verbose_name='Фамилия'),
        ),
    ]
