# Generated by Django 5.1 on 2024-08-21 19:38

import config.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_published', models.BooleanField(default=True, help_text='Если уже неактуально, но может понадобиться, снимите флажок', verbose_name='Актуально на сайте')),
                ('name', models.CharField(help_text='Текст не более 100 символов (цифры запрещены)', max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я ]+$')], verbose_name='Название')),
                ('category', models.CharField(choices=[('1', 'Документы'), ('2', 'Отчетность'), ('3', 'Уставные документы')], verbose_name='Категория')),
                ('link', models.FileField(help_text='Добавьте документ (обязательно)', upload_to=config.utils.docs_path, verbose_name='Ссылка')),
                ('description', models.TextField(help_text='Текстовое поле без ограничений', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='OrganizationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_published', models.BooleanField(default=True, help_text='Если уже неактуально, но может понадобиться, снимите флажок', verbose_name='Актуально на сайте')),
                ('name', models.CharField(help_text='Текст не более 100 символов (цифры запрещены)', max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я ]+$')], verbose_name='Название')),
                ('legal_address', models.CharField(help_text='Текст не более 200 символов', max_length=200, verbose_name='Юридический адрес')),
                ('address', models.CharField(help_text='Текст не более 200 символов', max_length=200, verbose_name='Физический адрес')),
                ('ogrn_number', models.CharField(help_text='Состоит из 13 цифр', max_length=13, validators=[django.core.validators.RegexValidator(regex='\\d{13}')], verbose_name='ОГРН')),
                ('inn_number', models.CharField(help_text='Состоит из 10 цифр', max_length=10, validators=[django.core.validators.RegexValidator(regex='\\d{10}')], verbose_name='ИНН')),
                ('kpp_number', models.CharField(help_text='Состоит из 9 цифр', max_length=9, validators=[django.core.validators.RegexValidator(regex='\\d{9}')], verbose_name='КПП')),
                ('current_account', models.CharField(help_text='Состоит из 20 цифр', max_length=20, validators=[django.core.validators.RegexValidator(regex='\\d{20}')], verbose_name='Расчетный счет')),
                ('bik', models.CharField(help_text='Состоит из 9 цифр', max_length=9, validators=[django.core.validators.RegexValidator(regex='\\d{9}')], verbose_name='БИК')),
                ('correspondent_account', models.CharField(help_text='Состоит из 20 цифр', max_length=20, validators=[django.core.validators.RegexValidator(regex='\\d{20}')], verbose_name='Корр. счет')),
                ('director', models.CharField(help_text='Текст не более 100 символов (цифры запрещены)', max_length=100, validators=[django.core.validators.RegexValidator(regex='\\D')], verbose_name='Директор')),
                ('link', models.ImageField(blank=True, help_text='Отправляет на страницу, откуда можно сделать пожертвование на нужды организации (необязательно)', upload_to=config.utils.docs_path, verbose_name='QR-код банка')),
            ],
            options={
                'verbose_name': 'Реквизиты организации',
                'verbose_name_plural': 'Реквизиты организации',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_published', models.BooleanField(default=True, help_text='Если уже неактуально, но может понадобиться, снимите флажок', verbose_name='Актуально на сайте')),
                ('name', models.CharField(help_text='Текст не более 100 символов (цифры запрещены)', max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я]+$')], verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Текст не более 100 символов (цифры запрещены)', max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я]+$')], verbose_name='Фамилия')),
                ('role', models.CharField(help_text='Текст не более 100 символов (цифры запрещены)', max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я ]+$')], verbose_name='Роль в проекте')),
                ('link', models.ImageField(blank=True, help_text='Добавьте фото (необязательно)', null=True, upload_to=config.utils.docs_path, verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Члена команды',
                'verbose_name_plural': 'Члены команды',
            },
        ),
    ]
