# Generated by Django 5.1 on 2024-10-20 10:07

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_app', '0002_alter_document_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdetail',
            name='link',
            field=models.ImageField(blank=True, help_text='Добавьте QR-код банка (необязательно)', null=True, upload_to=config.utils.docs_path, validators=[config.utils.validate_file_size], verbose_name='QR-код банка'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='link',
            field=models.ImageField(blank=True, help_text='Добавьте Фото (необязательно)', null=True, upload_to=config.utils.docs_path, validators=[config.utils.validate_file_size], verbose_name='Фото'),
        ),
    ]
