# Generated by Django 5.1 on 2024-08-25 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_app', '0002_remove_organizationdetail_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(help_text='Текст без ограничений', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(help_text='Текст не более 100 символов', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='last_name',
            field=models.CharField(help_text='Только буквы не более 50 символов', max_length=50, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(help_text='Только буквы не более 50 символов', max_length=50, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(help_text='Текст не более 100 символов (цифры запрещены)', max_length=100, validators=[django.core.validators.RegexValidator(regex='[^[^0-9]+$')], verbose_name='Роль в проекте'),
        ),
    ]
