# Generated by Django 5.1 on 2024-08-20 10:33

import about_us_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_app', '0002_alter_teammember_options_alter_teammember_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=about_us_app.models.team_member_photo_path, verbose_name='Фотография'),
        ),
    ]
