# Generated by Django 5.1 on 2024-10-20 10:24

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_app', '0003_alter_organizationdetail_link_alter_teammember_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='link',
            field=models.FileField(help_text='Добавьте Документ ', upload_to=config.utils.docs_path, validators=[config.utils.validate_file_size], verbose_name='Документ'),
        ),
    ]
