# Generated by Django 5.1 on 2024-10-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_app', '0004_alter_document_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Если уже неактуально, но может понадобиться, снимите флажок', verbose_name='Актуально на сайте'),
        ),
        migrations.AlterField(
            model_name='organizationdetail',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Если уже неактуально, но может понадобиться, снимите флажок', verbose_name='Актуально на сайте'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Если уже неактуально, но может понадобиться, снимите флажок', verbose_name='Актуально на сайте'),
        ),
    ]
