# Generated by Django 5.1 on 2024-09-10 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_app', '0004_alter_document_name_alter_organizationdetail_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdetail',
            name='director',
            field=models.CharField(default='Иванов Иван Иванович', help_text='Только буквы не более 50 символов', max_length=200, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я]+$')], verbose_name='ФИО директора'),
        ),
    ]
