# Generated by Django 5.1 on 2024-11-11 20:36

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_app', '0005_alter_document_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_published', models.BooleanField(default=True, help_text='Если уже неактуально, но может понадобиться, снимите флажок', verbose_name='Актуально на сайте')),
                ('name', models.CharField(help_text='Текст не более 255 символов', max_length=255, verbose_name='Пользовательское соглашение')),
                ('link', models.FileField(help_text='Добавьте Пользовательское соглашение ', upload_to=config.utils.docs_path, validators=[config.utils.validate_file_size], verbose_name='Пользовательское соглашение')),
            ],
            options={
                'verbose_name': 'Пользовательское соглашение',
                'verbose_name_plural': 'Пользовательское соглашение',
            },
        ),
    ]
