# Generated by Django 5.1 on 2024-09-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_app', '0006_alter_organizationdetail_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdetail',
            name='name',
            field=models.CharField(help_text='Текст не более 100 символов (цифры запрещены)', max_length=300, verbose_name='Название'),
        ),
    ]
