# Generated by Django 5.1 on 2024-09-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_app', '0007_alter_organizationdetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(help_text='Текст не более 100 символов (цифры запрещены)', max_length=100, verbose_name='Роль в проекте'),
        ),
    ]
