# Generated by Django 5.1 on 2024-10-02 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_app', '0009_teammember_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(help_text='Текст, не более 1000 символов', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(help_text='Текст не более 300 символов', max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='organizationdetail',
            name='address',
            field=models.CharField(help_text='Текст не более 300 символов', max_length=300, verbose_name='Физический адрес'),
        ),
        migrations.AlterField(
            model_name='organizationdetail',
            name='legal_address',
            field=models.CharField(help_text='Текст не более 300 символов', max_length=300, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='organizationdetail',
            name='name',
            field=models.CharField(help_text='Текст не более 300 символов (цифры запрещены)', max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='last_name',
            field=models.CharField(help_text='Только буквы не более 100 символов', max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(help_text='Только буквы не более 100 символов', max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я]+$')], verbose_name='Отчество'),
        ),
    ]
