<<<<<<< HEAD
# Generated by Django 5.1 on 2024-10-15 14:32
=======
# Generated by Django 5.1 on 2024-10-15 07:25
>>>>>>> origin/андрей

import config.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_app', '0010_alter_document_description_alter_document_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(help_text='Не более 1000 символов', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='document',
            name='link',
            field=models.FileField(help_text='Добавьте Документ', upload_to=config.utils.docs_path, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(help_text='Текст не более 255 символов', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='organizationdetail',
            name='address',
            field=models.CharField(help_text='Текст не более 255 символов', max_length=255, verbose_name='Физический адрес'),
        ),
        migrations.AlterField(
            model_name='organizationdetail',
            name='director',
            field=models.CharField(help_text="Только буквы и ('-', ' ') не более 255 символов ", max_length=255, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я- ]+$')], verbose_name='ФИО директора'),
        ),
        migrations.AlterField(
            model_name='organizationdetail',
            name='legal_address',
            field=models.CharField(help_text='Текст не более 255 символов', max_length=255, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='organizationdetail',
            name='link',
            field=models.ImageField(blank=True, help_text='Добавьте QR-код банка (необязательно)', null=True, upload_to=config.utils.docs_path, verbose_name='QR-код банка'),
        ),
        migrations.AlterField(
            model_name='organizationdetail',
            name='name',
            field=models.CharField(help_text='Текст не более 255 символов', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='last_name',
            field=models.CharField(help_text="Только буквы и ('-',) не более 100 символов ", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='link',
            field=models.ImageField(blank=True, help_text='Добавьте Фото (необязательно)', null=True, upload_to=config.utils.docs_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(help_text="Только буквы и ('-',) не более 100 символов ", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(help_text='Текст не более 100 символов', max_length=100, verbose_name='Роль в проекте'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='surname',
            field=models.CharField(blank=True, help_text="Только буквы и (' ',) не более 100 символов (необязательно)", max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я ]+$')], verbose_name='Отчество'),
        ),
    ]
