# Generated by Django 5.1 on 2024-10-20 10:07

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='link',
            field=models.ImageField(blank=True, help_text='Добавьте Изображение (необязательно)', null=True, upload_to=config.utils.docs_path, validators=[config.utils.validate_file_size], verbose_name='Изображение'),
        ),
    ]
