# Generated by Django 5.1 on 2024-10-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_alter_newsimage_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(help_text='Не более 1000 символов', max_length=1000, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Текст не более 255 символов', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.URLField(blank=True, help_text='Введите ссылку, не более 255 символов', max_length=255, null=True, verbose_name='Видео'),
        ),
    ]
