# Generated by Django 5.1 on 2024-11-11 20:36

import config.validators
import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Только буквы и ('-',) не более 100 символов ", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Имя')),
                ('lastname', models.CharField(help_text="Только буквы и ('-',) не более 100 символов ", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Фамилия')),
                ('content', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000, 'Комментарий не может быть длиннее 1000 символов.'), config.validators.validate_no_mixed_scripts, config.validators.validate_number_of_spaces_or_dashes, config.validators.validate_comment], verbose_name='Чем хотите помочь')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Введите Номер телефона ', max_length=128, region='RU', verbose_name='Номер телефона')),
                ('email', models.EmailField(help_text='Введите email: example@mail.com', max_length=254, verbose_name='email Электронная почта')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Предложение помощи',
                'verbose_name_plural': 'Предложения помощи',
            },
        ),
    ]
