# Generated by Django 5.1 on 2024-10-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_alter_projectimage_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Текст не более 150 символов', max_length=150, verbose_name='Название проекта'),
        ),
    ]
