# Generated by Django 5.1 on 2024-09-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_rename_news_projectimage_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Только буквы не более 50 символов', max_length=300, verbose_name='Наименование проекта'),
        ),
    ]
