# Generated by Django 5.1 on 2024-08-20 21:00

import feedback_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('lastname', models.CharField(max_length=100, verbose_name='фамилия')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='отчество')),
                ('preview', models.ImageField(blank=True, null=True, upload_to=feedback_app.models.feedback_preview_path, verbose_name='фотография')),
                ('date_create', models.DateTimeField(blank=True, null=True, verbose_name='дата создания')),
                ('content', models.TextField(blank=True, db_index=True, verbose_name='содержимое')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
