# Generated by Django 5.1 on 2024-10-18 23:40

import config.utils
import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Только буквы и ('-',) не более 100 символов ", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Имя')),
                ('lastname', models.CharField(help_text="Только буквы и ('-',) не более 100 символов ", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Фамилия')),
                ('link', models.ImageField(blank=True, help_text='Добавьте Фото (необязательно)', null=True, upload_to=config.utils.docs_path, verbose_name='Фото')),
                ('content', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000, 'Комментарий не может быть длиннее 1000 символов.'), config.validators.validate_no_mixed_scripts, config.validators.validate_number_of_spaces_or_dashes, config.validators.validate_comment], verbose_name='Текст отзыва')),
                ('date_create', models.DateTimeField(verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
