# Generated by Django 5.1 on 2024-08-25 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='surname',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(blank=True, db_index=True, help_text='Текст без ограничений', verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='lastname',
            field=models.CharField(help_text='Только буквы не более 50 символов', max_length=50, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(help_text='Только буквы не более 50 символов', max_length=50, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я]+$')], verbose_name='Имя'),
        ),
    ]
