# Generated by Django 5.1 on 2024-09-06 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_remove_feedback_surname_alter_feedback_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='lastname',
            field=models.CharField(help_text='Только буквы не более 50 символов', max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(help_text='Только буквы не более 50 символов', max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я]+$')], verbose_name='Имя'),
        ),
    ]
