# Generated by Django 5.1 on 2024-10-20 10:07

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_alter_feedback_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='link',
            field=models.ImageField(blank=True, help_text='Добавьте Фото (необязательно)', null=True, upload_to=config.utils.docs_path, validators=[config.utils.validate_file_size], verbose_name='Фото'),
        ),
    ]
