# Generated by Django 5.1 on 2024-10-02 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0004_alter_feedback_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(blank=True, db_index=True, help_text='Текст, не более 1000 символов', max_length=1000, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='lastname',
            field=models.CharField(help_text='Только буквы не более 100 символов', max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(help_text='Только буквы не более 100 символов', max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я]+$')], verbose_name='Имя'),
        ),
    ]
