# Generated by Django 5.1 on 2024-10-16 17:42

import config.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0005_alter_feedback_content_alter_feedback_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(help_text='Не более 1000 символов', max_length=1000, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='lastname',
            field=models.CharField(help_text="Только буквы и ('-',) не более 100 символов ", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='link',
            field=models.ImageField(blank=True, help_text='Добавьте Фото (необязательно)', null=True, upload_to=config.utils.docs_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(help_text="Только буквы и ('-',) не более 100 символов ", max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я-]+$')], verbose_name='Имя'),
        ),
    ]
